export const GET_DATA_LOADING = "GET_DATA_LOADING";
export const GET_DATA_SUCCESS = "GET_DATA_SUCCESS";
export const GET_DATA_ERROR = "GET_DATA_ERROR";

export const PAGE_CHANGE = "PAGE_CHANGE";

export const SEARCH_RESULT = "SEARCH_RESULT";